# Generated by Django 4.1.3 on 2022-11-09 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('Account', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'HR'), (2, 'EMPLOYEE')], null=True)),
                ('date_of_birth', models.DateField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='user/profile_pictures')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='user/cover_photos')),
                ('permanent_address', models.CharField(blank=True, max_length=250, null=True)),
                ('permanent_country', models.CharField(blank=True, max_length=15, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=15, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=15, null=True)),
                ('permanent_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('present_address', models.CharField(blank=True, max_length=250, null=True)),
                ('present_country', models.CharField(blank=True, max_length=15, null=True)),
                ('present_state', models.CharField(blank=True, max_length=15, null=True)),
                ('present_city', models.CharField(blank=True, max_length=15, null=True)),
                ('present_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=12, null=True)),
                ('date_of_joining', models.DateTimeField()),
                ('date_of_termination', models.DateTimeField()),
                ('pan_card_no', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhaar_card', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
