# Generated by Django 4.1.3 on 2022-11-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_date_of_birth_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_joining',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_termination',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
