# Generated by Django 4.1.3 on 2022-11-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_leaveapplication_educationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
