# Generated by Django 4.1.3 on 2022-11-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_leaveapplication_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationdetails',
            options={'verbose_name_plural': 'Education Details'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Account',
            new_name='account',
        ),
    ]
