# Generated by Django 4.1.3 on 2022-11-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_educationdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='reason',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PAID'), (2, 'UNPAID')], default=2),
        ),
    ]
